### ISSUE TITLE
Is there any way to not use trial mass?

### ISSUE THREAD

**Issue by daltonspider** [MagedMohamedTurk/Turbomachinery-Rotors-Balancing#3]
I would like to balance a turbine rotor but only by sanding or drilling the unbalanced blades. Is there any way to not use trial mass? Just analyzing vibration and rpm? Congratulations for the incredible work!

**Comment by fburgos01** [comment]
1. You can't know how much you are "sanding", drilling on the other side it's straightforward, get the density of your material (kg/m^3) and multiply by the volume of the drill.

2. It's very unlikely this could be done without an extensive knowledge of the rotor detailed construction, material, foundations, etc. Any way I remember reading an article using a force hammer to get the response on the bearings and correlate it to the force of the rotor for the test mass and do "one shot balance"

**Comment by MagedMohamedTurk** [comment]
@daltonspider Thanks for your question and hope the project has been useful for you. 
As @fburgos01 explained, sanding is not the best practice for balancing because you can't control the weight removed accurately.
Usually your blades either need sandblasting or not, depends only on the condition of erosion and corrosion in metal.
Secondly, your question on whether we can do the balancing with no trial weights and thus with less startup and shutdown. This is actually one million dollar question :smile: 
The subject, usually referred to as "One Shot Balancing", has been handled by many. I believe what @fburgos01 was trying to say is as mentioned in this PDF: www.shorturl.at/cfI01. This method is usually limited to rigid rotors (where speed does not exceed the first critical) and I think it is not either easy or guaranteed.
One easier way is to use the previous balancing data for the machine to calculate your Influence Coefficient Matrix, and with your initial conditions you can conclude directly the trimming weights required. You can use Hsbalance in this manner by creating a "ALPHA" matrix using the previous balancing data sheet and use this matrix in new model with your initial conditions.
I recommend also to visit www.maintenance.org for other useful discussions.
